version: '3'

networks:
  mynetwork:

services:
  dash_app:
    build:
      context: ./app
    ports:
      - "8050:8050"
    depends_on:
      - scraping_api
      - db_api
    networks:
      - mynetwork

  scraping_api:
    container_name: scraping_api
    build:
      context: ./api
      dockerfile: ./scraper/Dockerfile
    ports:
      - "5001:5001"
    networks:
      - mynetwork

  db_api:
    container_name: db_api
    build:
      context: ./api
      dockerfile: ./db/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_DATABASE=job_scrapping
    networks:
      - mynetwork
    depends_on: 
      - mysql

  mysql:
      image: mysql:latest
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: job_scrapping
      ports:
        - "3306:3306"
      volumes:
        - ./assets/db_structure/job_scrapping.sql:/docker-entrypoint-initdb.d/job_scrapping.sql
      networks:
        - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mynetwork
